enterprise/urls.py
from django.conf.urls import patterns, url
# from django.core.urlresolvers import reverse
from enterprise import views


urlpatterns = patterns('',
                       url(r'^register/$', views.register, name='register'),
                       url(r'^add_ass/$', 'enterprise.views.add_ass', name='add_ass'),
                       url(r'^add_prod/$', 'enterprise.views.add_prod', name='add_tprod'),

                       url(r'^add_product/$', 'enterprise.views.add_product', name='add_product'),
                       url(r'^add_asset/$', 'enterprise.views.add_asset', name='add_asset'),
                       url(r'^add_type/$', 'enterprise.views.add_type', name='add_type'),
                       url(r'^add_material/$', 'enterprise.views.add_material', name='add_material'),
                       url(r'^add_operation/$', 'enterprise.views.add_operation', name='add_operation'),
                       url(r'^edit/(?P<slug>[^/]+)/$', 'enterprise_profile.views.enterprise_profile_edit',
                           name='enterprise_profile_edit'),
                       url(r'^(?P<slug>[^/]+)/$', 'enterprise_profile.views.enterprise_profile',
                           name='enterprise_profile'),
                       url(r'^(?P<slug>[^/]+)/aj$', 'enterprise_profile.views.enterprise_profile_aj',
                           name='enterprise_profile_aj'),

                       url(r'^(?P<slug>[^/]+)/products/$', 'enterprise.views.product', name='product'),
                       url(r'^(?P<slug>[^/]+)/people/$', 'enterprise.views.people', name='people'),
                       url(r'^(?P<slug>[^/]+)/about/$', 'enterprise.views.about', name='about'),
                       url(r'^(?P<slug>[^/]+)/capability/$', 'enterprise.views.capability', name='capability'),

)


# urlpatterns += patterns('django.contrib.auth.views',
#         url(r'^login/$', 'login', { 'template_name': 'registration/login.html'}, name='login' ),
#         url(r'^logout/$', 'logout', { 'template_name': 'registration/my_account.html', 'next_page':reverse('index') }, name='logout' ),
# )

ilog_dev/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.views.generic import TemplateView
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = patterns('',

                       url(r'^admin/', include(admin.site.urls)), # admin interface

                       url(r'^$', 'myuserprofile.views.home', name='home'), # home page
                       url(r'^logup$', 'accounts.views.logup', name='logup'), # logup page
                       url(r'^login$', 'django.contrib.auth.views.login', {'template_name': 'login.html'}, name='login'),  # login page, redirects to 'home'
                       url(r'^logout$', 'django.contrib.auth.views.logout', {'next_page': 'login'}, name='logout'), # logout page, redirects to 'login'

                       url(r'^accounts/', include('accounts.urls', namespace='accounts')), # no use for now
                       url(r'^enterprise/', include('enterprise.urls', namespace='enterprise')),  # enterprise domain
                       url(r'^user/', include('myuserprofile.urls', namespace='myuserprofile')), # user domain
                       url(r'^nodes/', include('nodes.urls', namespace='nodes')),
                       url(r'^relationships/', include('relationships.urls', namespace='relationships')),

                       url(r'^messages/', include('message.urls', namespace='messages')),
                       url(r'^like/$', 'nodes.views.like', name='like'),
                       url(r'^search/$', 'search.views.search', name='search'),
                       # url(r'^search_adv/$', 'search.views.search_adv', name='search_adv'),

                       url(r'^images/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
                       url(r'^notifications/$', 'activities.views.notifications', name='notifications'),

                       url(r'^robots.txt/$', TemplateView.as_view(template_name='robots.txt')),

)   + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# urlpatterns += patterns('',
#                         (r'^media/(?P<path>.*)$', 'django.views.static.serve', {
#                          'document_root': settings.MEDIA_ROOT}))

# urlpatterns = patterns('',
# urlpatterns += staticfiles_urlpatterns()
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

nodes/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('nodes.views',
                       url(r'^$', 'nodes', name='nodes'),
                       url(r'^post/$', 'post', name='post'),
                       url(r'^comment/$', 'comment', name='comment'),
                       url(r'^like/$', 'like', name='like'),
                       # url(r'^post/$', 'post', name='post'),
                       # url(r'^unlike/$', 'unlike', name='unlike'),
#     url(r'^like/$', 'like', name='like'),
#     url(r'^comment/$', 'comment', name='comment'),
#     url(r'^load/$', 'load', name='load'),
#     url(r'^check/$', 'check', name='check'),
#     url(r'^load_new/$', 'load_new', name='load_new'),
#     url(r'^update/$', 'update', name='update'),
#     url(r'^track_comments/$', 'track_comments', name='track_comments'),
#     url(r'^remove/$', 'remove', name='remove_feed'),
#     url(r'^(\d+)/$', 'feed', name='feed'),
)

enterprise/forms.py
from django import forms
from django.core.exceptions import ValidationError
from enterprise.models import *


def unique_enterprise_validator(value):
    if Enterprise.objects.filter(enterprise__iexact=value).exists():
        raise ValidationError("This enterprise already exists")


class EnterpriseRegistrationForm(forms.ModelForm):
    enterprise = forms.CharField(max_length=255, help_text='If you give a name like "Abc Enterprises, you will get a url like www.industrylogger.com/enterprises/abc-enterprises')
    types = forms.ModelMultipleChoiceField(queryset=Type.objects.all(), required=False, help_text='Select one or more  Use Ctrl to select more than one')
    # assets = forms.ModelMultipleChoiceField(queryset=Asset.objects.all(), required=False)
    # products = forms.ModelMultipleChoiceField(queryset=Product.objects.all(), required=False)
    materials = forms.ModelMultipleChoiceField(queryset=Material.objects.all(), required=False, help_text='Select one or more  Use Ctrl to select more than one')
    operations = forms.ModelMultipleChoiceField(queryset=Operation.objects.all(), required=False, help_text='Select one or more  Use Ctrl to select more than one')


    class Meta:
        model = Enterprise
        exclude = ['slug', 'products', 'assets',]
        fields = ['enterprise', 'types', 'materials', 'operations', ]

    def __init__(self, *args, **kwargs):
        super(EnterpriseRegistrationForm, self).__init__(*args, **kwargs)
        self.fields['enterprise'].validators.append(unique_enterprise_validator)


class ProductForm(forms.ModelForm):
    prod = forms.CharField()
    description = forms.CharField(widget=forms.Textarea, max_length=500, required=False)
    product_image = forms.ImageField(required=False)
    caption = forms.CharField(max_length=255, required=False)

    class Meta:
        model = EnterpriseProduct
        exclude = ['enterprise', 'status']
        fields = ['prod', 'product_image', 'description', 'caption']


class AssetForm(forms.ModelForm):
    asse = forms.CharField()
    description = forms.CharField(widget=forms.Textarea, max_length=500, required=False)
    asset_image = forms.ImageField(required=False)
    caption = forms.CharField(max_length=255, required=False)

    class Meta:
        model = EnterpriseAsset
        exclude = ['enterprise', 'status']
        fields = ['asse', 'asset_image', 'description', 'caption']


class TypeForm(forms.ModelForm):
    name = forms.CharField(max_length=50)

    class Meta:
        model = Type
        exclude = ['slug', 'is_active']
        fields = ['name']


class MaterialForm(forms.ModelForm):
    name = forms.CharField(max_length=50)

    class Meta:
        model = Material
        exclude = ['slug', 'is_active', ]
        fields = ['name']


class OperationForm(forms.ModelForm):
    name = forms.CharField(max_length=50)

    class Meta:
        model = Operation
        exclude = ['slug', 'is_active', ]
        fields = ['name']


class ProdForm(forms.ModelForm):
    name = forms.CharField(max_length=50)

    class Meta:
        model = Product
        exclude = ['slug', 'is_active', ]
        fields = ['name']

class AssForm(forms.ModelForm):
    name = forms.CharField(max_length=50)

    class Meta:
        model = Asset
        exclude = ['slug', 'is_active', ]
        fields = ['name']

enterprise/views.py
from django.shortcuts import render, redirect, get_object_or_404
from enterprise.forms import *
from enterprise.models import *
from nodes.models import Node
from accounts.models import MyUser
from django.contrib.auth.decorators import login_required


def register(request):
    if request.method == "POST":
        form = EnterpriseRegistrationForm(request.POST)
        if not form.is_valid():
            print("form invalid")
            render(request, 'enterprise/register.html', {'form': form})
        else:
            enterprise = form.cleaned_data.get('enterprise')
            types = form.cleaned_data.get('types')
            # assets = form.cleaned_data.get('assets')

            operations = form.cleaned_data.get('operations')
            materials = form.cleaned_data.get('materials')

            # t, created= Type.objects.get_or_create(name=types)
            # a, creted = Asset.objects.get_or_create(name=assets)
            er = Enterprise.objects.create(enterprise=enterprise,)
            er.types = types
            # er.assets = assets
            er.operations = operations
            er.materials = materials

            welcome = u'{0} is now in the network, have a look at its profile.'.format(enterprise)
            node = Node(myuser=MyUser.objects.get(pk=1), post=welcome)
            node.save()

            return redirect('/accounts/logup')
    else:
        return render(request, 'enterprise/register.html', {'form': EnterpriseRegistrationForm()})

@login_required
def add_product(request):
    enterprise = request.user.enterprise
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES)

        if not form.is_valid():

            render(request, 'products/add_product.html', {'form': form})
        else:

            product = form.cleaned_data.get('prod')
            description = form.cleaned_data.get('description')
            product_image = form.cleaned_data.get('product_image')
            caption = form.cleaned_data.get('caption')

            p, created = Product.objects.get_or_create(name=product)

            ep = EnterpriseProduct.objects.create(product=p, enterprise=enterprise, description=description,
                                                  caption=caption, product_image=product_image,
                                                  product_image_thumbnail=product_image)

            return redirect('/enterprise/'+enterprise.slug)
    else:
        return render(request, 'products/add_product.html', {'form': ProductForm()})

@login_required
def add_asset(request):
    enterprise = request.user.enterprise
    if request.method == 'POST':
        form = AssetForm(request.POST, request.FILES)

        if not form.is_valid():

            render(request, 'asset/add_asset.html', {'form': form})  ##
        else:

            asset = form.cleaned_data.get('asse')
            description = form.cleaned_data.get('description')
            asset_image = form.cleaned_data.get('asset_image')
            caption = form.cleaned_data.get('caption')

            a, created = Asset.objects.get_or_create(name=asset)

            ep = EnterpriseAsset.objects.create(asset=a, enterprise=enterprise, description=description,
                                                  caption=caption, asset_image=asset_image,
                                                  asset_image_thumbnail=asset_image)

            return redirect('/enterprise/add_asset')
    else:
        return render(request, 'assets/add_asset.html', {'form': AssetForm()})


def product(request, slug):
    page_enterprise = get_object_or_404(Enterprise, slug=slug)
    products = EnterpriseProduct.objects.filter(enterprise=page_enterprise)
    product_intro = page_enterprise.enterpriseprofile.product_intro

    return render(request, 'products/products.html', {
        'page_enterprise': page_enterprise,
        'products': products,
        'product_intro': product_intro,
        })


def people(request, slug):
    page_enterprise = get_object_or_404(Enterprise, slug=slug)
    members = MyUser.objects.filter(enterprise=page_enterprise)
    people_detail = page_enterprise.enterpriseprofile.people_detail

    return render(request, 'products/people.html', {
        'page_enterprise': page_enterprise,
        'members': members,
        'people_detail': people_detail,
        })

def about(request, slug):
    page_enterprise = get_object_or_404(Enterprise, slug=slug)
    types = page_enterprise.types.all()
    about = page_enterprise.enterpriseprofile.about
    website = page_enterprise.enterpriseprofile.website

    return render(request, 'products/about.html', {
        'types': types,
        'about': about,
        'page_enterprise': page_enterprise,
        'website': website,
        })

def capability(request, slug):
    page_enterprise = get_object_or_404(Enterprise, slug=slug)
    assets = EnterpriseAsset.objects.filter(enterprise=page_enterprise)
    operations = page_enterprise.operations.all()
    capabilities = page_enterprise.enterpriseprofile.capabilities

    return render(request, 'products/capability.html', {
        'assets': assets,
        'operations': operations,
        'page_enterprise': page_enterprise,
        'capabilities': capabilities,
        })


def add_type(request):
    form = TypeForm(request.POST)
    if request.method == 'POST':

        if not form.is_valid():
            render(request, 'enterprise/add_type.html', {'form': form})
        else:
            name = form.cleaned_data.get('name')

            t, created = Type.objects.get_or_create(name=name)

            t.save()
            return redirect('/enterprise/register')

    else:
        return render(request, 'enterprise/add_type.html', {'form': form})

def add_operation(request):
    form = OperationForm(request.POST)
    if request.method == 'POST':

        if not form.is_valid():
            render(request, 'enterprise/add_operation.html', {'form': form})
        else:
            name = form.cleaned_data.get('name')
            o, created = Operation.objects.get_or_create(name=name)
            o.save()
            return redirect('/enterprise/register')

    else:
        return render(request, 'enterprise/add_operation.html', {'form': form})


def add_material(request):
    form = MaterialForm(request.POST)
    if request.method == 'POST':

        if not form.is_valid():
            render(request, 'enterprise/add_material.html', {'form': form})
        else:
            name = form.cleaned_data.get('name')
            m, created = Material.objects.get_or_create(name=name)
            m.save()
            return redirect('/enterprise/register')

    else:
        return render(request, 'enterprise/add_material.html', {'form': form})


def add_prod(request):
    form = ProdForm(request.POST)
    if request.method == 'POST':

        if not form.is_valid():
            render(request, 'enterprise/add_prod.html', {'form': form})
        else:
            name = form.cleaned_data.get('name')

            t, created = Product.objects.get_or_create(name=name)

            t.save()
            return redirect('/enterprise/add_prod')

    else:
        return render(request, 'enterprise/add_prod.html', {'form': form})


def add_ass(request):
    form = AssForm(request.POST)
    if request.method == 'POST':

        if not form.is_valid():
            render(request, 'enterprise/add_ass.html', {'form': form})
        else:
            name = form.cleaned_data.get('name')

            t, created = Asset.objects.get_or_create(name=name)

            t.save()
            return redirect('/enterprise/add_ass')

    else:
        return render(request, 'enterprise/add_ass.html', {'form': form})
# Create your views here.

templates/enterprise/add_ass.html
{% extends "home.html" %}
{% load staticfiles %}

{% block menu_links %}
    <li class="link"><a href="{% url 'enterprise:register' %}">Back</a></li>
{% endblock %}

{% block content %}
	<section id="content_add_type" class="contents">
		<header class="header_form">
			<h2>Add a new type only if you cant fit in any of the existing type as 
			it will reduce the probability of your company showing up in our advanced search feature</h2>
		</header>
		<form id="form_add_type" class="forms_home" action="/enterprise/add_ass/" method="POST" role="form">
			<ul class="uls_home">
				{{ form.as_ul }}
				{% csrf_token %}
				<li><input type="submit" value="submit" class="submit_main"></li>
			</ul>
		</form>
	</section>
{% endblock %}

templates/enterprise/add_material.html
{% extends "home.html" %}
{% load staticfiles %}

{% block menu_links %}
    <li class="link"><a href="{% url 'enterprise:register' %}">Back</a></li>
{% endblock %}

{% block content %}
	<section id="content_add_type" class="contents">
		<header class="header_form">
			<h2>Add a new material only if you cant fit in any of the existing type as 
			it will reduce the probability of your company showing up in our advanced search feature</h2>
		</header>
		<form id="form_add_type" class="forms_home" action="/enterprise/add_material/" method="POST" role="form">
			<ul class="uls_home">
				{{ form.as_ul }}
				{% csrf_token %}
				<li><input type="submit" value="submit" class="submit_main"></li>
			</ul>
		</form>
	</section>
{% endblock %}

templates/enterprise/add_operation.html
{% extends "home.html" %}
{% load staticfiles %}

{% block menu_links %}
    <li class="link"><a href="{% url 'enterprise:register' %}">Back</a></li>
{% endblock %}

{% block content %}
	<section id="content_add_type" class="contents">
		<header class="header_form">
			<h2>Add a new operation only if you cant fit in any of the existing type as 
			it will reduce the probability of your company showing up in our advanced search feature</h2>
		</header>
		<form id="form_add_type" class="forms_home" action="/enterprise/add_operation/" method="POST" role="form">
			<ul class="uls_home">
				{{ form.as_ul }}
				{% csrf_token %}
				<li><input type="submit" value="submit" class="submit_main"></li>
			</ul>
		</form>
	</section>
{% endblock %}

templates/enterprise/add_prod.html
{% extends "home.html" %}
{% load staticfiles %}

{% block menu_links %}
    <li class="link"><a href="{% url 'enterprise:register' %}">Back</a></li>
{% endblock %}

{% block content %}
	<section id="content_add_type" class="contents">
		<header class="header_form">
			<h2>Add a new type only if you cant fit in any of the existing type as 
			it will reduce the probability of your company showing up in our advanced search feature</h2>
		</header>
		<form id="form_add_type" class="forms_home" action="/enterprise/add_prod/" method="POST" role="form">
			<ul class="uls_home">
				{{ form.as_ul }}
				{% csrf_token %}
				<li><input type="submit" value="submit" class="submit_main"></li>
			</ul>
		</form>
	</section>
{% endblock %}

templates/enterprise/add_type.html
{% extends "home.html" %}
{% load staticfiles %}

{% block menu_links %}
    <li class="link"><a href="{% url 'enterprise:register' %}">Back</a></li>
{% endblock %}

{% block content %}
	<section id="content_add_type" class="contents">
		<header class="header_form">
			<h2>Add a new type only if you cant fit in any of the existing type as 
			it will reduce the probability of your company showing up in our advanced search feature</h2>
		</header>
		<form id="form_add_type" class="forms_home" action="/enterprise/add_type/" method="POST" role="form">
			<ul class="uls_home">
				{{ form.as_ul }}
				{% csrf_token %}
				<li><input type="submit" value="submit" class="submit_main"></li>
			</ul>
		</form>
	</section>
{% endblock %}

templates/enterprise/register.html
{% extends "home.html" %}

{% block menu_links %}
    <li class="link"><a href="{% url 'home' %}">Home</a></li>
    <li class="link"><a href="{% url 'logup' %}">Log Up</a></li>
{% endblock %}

{% block content %}
	<section id="content_register" class="contents">
		<header class="header_form">
			<h2>Register your company and be a part of this network.</h2>
		</header>
		<form id="form_register" class="forms_home" action="{% url 'enterprise:register' %}" method="POST" role="form" >
			<ul id="ul_register" class="uls_home">
				{{ form.as_ul }}
				{% csrf_token %}
				<div id="add">
					<h4><a href="{% url 'enterprise:add_type' %}">Add Type</a></h4>
					<h4><a href="{% url 'enterprise:add_material' %}">Add Material</a></h4>
					<h4><a href="{% url 'enterprise:add_operation' %}">Add Operation</a></h4>
				</div>
				<li><input id="submit_register" class="submit_main" type="submit" value="SAVE"></li>
			</ul>
		</form>

	</section>
{% endblock %}