enterprise/urls.py
from django.conf.urls import patterns, url
# from django.core.urlresolvers import reverse
from enterprise import views


urlpatterns = patterns('',
                       url(r'^register/$', views.register, name='register'),
                       url(r'^add_ass/$', 'enterprise.views.add_ass', name='add_ass'),
                       url(r'^add_prod/$', 'enterprise.views.add_prod', name='add_tprod'),

                       url(r'^add_product/$', 'enterprise.views.add_product', name='add_product'),
                       url(r'^add_asset/$', 'enterprise.views.add_asset', name='add_asset'),
                       url(r'^add_type/$', 'enterprise.views.add_type', name='add_type'),
                       url(r'^add_material/$', 'enterprise.views.add_material', name='add_material'),
                       url(r'^add_operation/$', 'enterprise.views.add_operation', name='add_operation'),
                       url(r'^edit/(?P<slug>[^/]+)/$', 'enterprise_profile.views.enterprise_profile_edit',
                           name='enterprise_profile_edit'),
                       url(r'^(?P<slug>[^/]+)/$', 'enterprise_profile.views.enterprise_profile',
                           name='enterprise_profile'),
                       url(r'^(?P<slug>[^/]+)/aj$', 'enterprise_profile.views.enterprise_profile_aj',
                           name='enterprise_profile_aj'),

                       url(r'^(?P<slug>[^/]+)/products/$', 'enterprise.views.product', name='product'),
                       url(r'^(?P<slug>[^/]+)/people/$', 'enterprise.views.people', name='people'),
                       url(r'^(?P<slug>[^/]+)/about/$', 'enterprise.views.about', name='about'),
                       url(r'^(?P<slug>[^/]+)/capability/$', 'enterprise.views.capability', name='capability'),

)


# urlpatterns += patterns('django.contrib.auth.views',
#         url(r'^login/$', 'login', { 'template_name': 'registration/login.html'}, name='login' ),
#         url(r'^logout/$', 'logout', { 'template_name': 'registration/my_account.html', 'next_page':reverse('index') }, name='logout' ),
# )

ilog_dev/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.views.generic import TemplateView
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = patterns('',

                       url(r'^admin/', include(admin.site.urls)), # admin interface

                       url(r'^$', 'myuserprofile.views.home', name='home'), # home page
                       url(r'^logup$', 'accounts.views.logup', name='logup'), # logup page
                       url(r'^login$', 'django.contrib.auth.views.login', {'template_name': 'login.html'}, name='login'),  # login page, redirects to 'home'
                       url(r'^logout$', 'django.contrib.auth.views.logout', {'next_page': 'login'}, name='logout'), # logout page, redirects to 'login'

                       url(r'^accounts/', include('accounts.urls', namespace='accounts')), # no use for now
                       url(r'^enterprise/', include('enterprise.urls', namespace='enterprise')),  # enterprise domain
                       url(r'^user/', include('myuserprofile.urls', namespace='myuserprofile')), # user domain
                       url(r'^nodes/', include('nodes.urls', namespace='nodes')),
                       url(r'^relationships/', include('relationships.urls', namespace='relationships')),

                       url(r'^messages/', include('message.urls', namespace='messages')),
                       url(r'^like/$', 'nodes.views.like', name='like'),
                       url(r'^search/$', 'search.views.search', name='search'),
                       # url(r'^search_adv/$', 'search.views.search_adv', name='search_adv'),

                       url(r'^images/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
                       url(r'^notifications/$', 'activities.views.notifications', name='notifications'),

                       url(r'^robots.txt/$', TemplateView.as_view(template_name='robots.txt')),

)   + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# urlpatterns += patterns('',
#                         (r'^media/(?P<path>.*)$', 'django.views.static.serve', {
#                          'document_root': settings.MEDIA_ROOT}))

# urlpatterns = patterns('',
# urlpatterns += staticfiles_urlpatterns()
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

message/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('message.views',
                       url(r'^$', 'inbox', name='inbox'),
                       url(r'^send/$', 'send', name='send_message'),
                       # url(r'^comment/$', 'comment', name='comment'),
                       # url(r'^like/$', 'like', name='like'),
                       # url(r'^post/$', 'post', name='post'),
                       # url(r'^unlike/$', 'unlike', name='unlike'),
#     url(r'^like/$', 'like', name='like'),
#     url(r'^comment/$', 'comment', name='comment'),
#     url(r'^load/$', 'load', name='load'),
#     url(r'^check/$', 'check', name='check'),
#     url(r'^load_new/$', 'load_new', name='load_new'),
#     url(r'^update/$', 'update', name='update'),
#     url(r'^track_comments/$', 'track_comments', name='track_comments'),
#     url(r'^remove/$', 'remove', name='remove_feed'),
#     url(r'^(\d+)/$', 'feed', name='feed'),
)

myuserprofile/urls.py
from django.conf.urls import patterns, url, include
from django.core.urlresolvers import reverse
from myuserprofile import views

urlpatterns = patterns('',
                       # url(r'^follow/$', views.follow, name='follow'),
                       # url(r'^unfollow/$', views.unfollow, name='unfollow'),
                       # url(r'^block/$', views.block, name='block'),
                       # url(r'^unblock/$', views.unblock, name='unblock'),
                       url(r'^edit/$', 'myuserprofile.views.profile_edit', name='profile_edit'),
                       url(r'^enterprises/$', 'myuserprofile.views.enterprises', name='enterprises'),
                       url(r'^people/$', 'myuserprofile.views.people', name='people'),
                       url(r'^skillset/$', 'myuserprofile.views.skillset', name='skillset'),
                       url(r'^relationships', include('relationships.urls', namespace='relationships')),
                       url(r'^(?P<slug>[^/]+)/$', 'myuserprofile.views.profile', name='profile'),
                       url(r'^(?P<slug>[^/]+)/$', 'myuserprofile.views.activity', name='activity'),



                       # url(r'^(?P<slug>[^/]+)/follow/$', 'myuserprofile.views.follow', name='follow'),
                       # url(r'^(?P<slug>[^/]+)/unfollow/$', 'myuserprofile.views.unfollow', name='unfollow'),
)

nodes/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('nodes.views',
                       url(r'^$', 'nodes', name='nodes'),
                       url(r'^post/$', 'post', name='post'),
                       url(r'^comment/$', 'comment', name='comment'),
                       url(r'^like/$', 'like', name='like'),
                       # url(r'^post/$', 'post', name='post'),
                       # url(r'^unlike/$', 'unlike', name='unlike'),
#     url(r'^like/$', 'like', name='like'),
#     url(r'^comment/$', 'comment', name='comment'),
#     url(r'^load/$', 'load', name='load'),
#     url(r'^check/$', 'check', name='check'),
#     url(r'^load_new/$', 'load_new', name='load_new'),
#     url(r'^update/$', 'update', name='update'),
#     url(r'^track_comments/$', 'track_comments', name='track_comments'),
#     url(r'^remove/$', 'remove', name='remove_feed'),
#     url(r'^(\d+)/$', 'feed', name='feed'),
)

enterprise/views.py
from django.shortcuts import render, redirect, get_object_or_404
from enterprise.forms import *
from enterprise.models import *
from nodes.models import Node
from accounts.models import MyUser
from django.contrib.auth.decorators import login_required


def register(request):
    if request.method == "POST":
        form = EnterpriseRegistrationForm(request.POST)
        if not form.is_valid():
            print("form invalid")
            render(request, 'enterprise/register.html', {'form': form})
        else:
            enterprise = form.cleaned_data.get('enterprise')
            types = form.cleaned_data.get('types')
            # assets = form.cleaned_data.get('assets')

            operations = form.cleaned_data.get('operations')
            materials = form.cleaned_data.get('materials')

            # t, created= Type.objects.get_or_create(name=types)
            # a, creted = Asset.objects.get_or_create(name=assets)
            er = Enterprise.objects.create(enterprise=enterprise,)
            er.types = types
            # er.assets = assets
            er.operations = operations
            er.materials = materials

            welcome = u'{0} is now in the network, have a look at its profile.'.format(enterprise)
            node = Node(myuser=MyUser.objects.get(pk=1), post=welcome)
            node.save()

            return redirect('/accounts/logup')
    else:
        return render(request, 'enterprise/register.html', {'form': EnterpriseRegistrationForm()})

@login_required
def add_product(request):
    enterprise = request.user.enterprise
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES)

        if not form.is_valid():

            render(request, 'products/add_product.html', {'form': form})
        else:

            product = form.cleaned_data.get('prod')
            description = form.cleaned_data.get('description')
            product_image = form.cleaned_data.get('product_image')
            caption = form.cleaned_data.get('caption')

            p, created = Product.objects.get_or_create(name=product)

            ep = EnterpriseProduct.objects.create(product=p, enterprise=enterprise, description=description,
                                                  caption=caption, product_image=product_image,
                                                  product_image_thumbnail=product_image)

            return redirect('/enterprise/'+enterprise.slug)
    else:
        return render(request, 'products/add_product.html', {'form': ProductForm()})

@login_required
def add_asset(request):
    enterprise = request.user.enterprise
    if request.method == 'POST':
        form = AssetForm(request.POST, request.FILES)

        if not form.is_valid():

            render(request, 'asset/add_asset.html', {'form': form})  ##
        else:

            asset = form.cleaned_data.get('asse')
            description = form.cleaned_data.get('description')
            asset_image = form.cleaned_data.get('asset_image')
            caption = form.cleaned_data.get('caption')

            a, created = Asset.objects.get_or_create(name=asset)

            ep = EnterpriseAsset.objects.create(asset=a, enterprise=enterprise, description=description,
                                                  caption=caption, asset_image=asset_image,
                                                  asset_image_thumbnail=asset_image)

            return redirect('/enterprise/add_asset')
    else:
        return render(request, 'assets/add_asset.html', {'form': AssetForm()})


def product(request, slug):
    page_enterprise = get_object_or_404(Enterprise, slug=slug)
    products = EnterpriseProduct.objects.filter(enterprise=page_enterprise)
    product_intro = page_enterprise.enterpriseprofile.product_intro

    return render(request, 'products/products.html', {
        'page_enterprise': page_enterprise,
        'products': products,
        'product_intro': product_intro,
        })


def people(request, slug):
    page_enterprise = get_object_or_404(Enterprise, slug=slug)
    members = MyUser.objects.filter(enterprise=page_enterprise)
    people_detail = page_enterprise.enterpriseprofile.people_detail

    return render(request, 'products/people.html', {
        'page_enterprise': page_enterprise,
        'members': members,
        'people_detail': people_detail,
        })

def about(request, slug):
    page_enterprise = get_object_or_404(Enterprise, slug=slug)
    types = page_enterprise.types.all()
    about = page_enterprise.enterpriseprofile.about
    website = page_enterprise.enterpriseprofile.website

    return render(request, 'products/about.html', {
        'types': types,
        'about': about,
        'page_enterprise': page_enterprise,
        'website': website,
        })

def capability(request, slug):
    page_enterprise = get_object_or_404(Enterprise, slug=slug)
    assets = EnterpriseAsset.objects.filter(enterprise=page_enterprise)
    operations = page_enterprise.operations.all()
    capabilities = page_enterprise.enterpriseprofile.capabilities

    return render(request, 'products/capability.html', {
        'assets': assets,
        'operations': operations,
        'page_enterprise': page_enterprise,
        'capabilities': capabilities,
        })


def add_type(request):
    form = TypeForm(request.POST)
    if request.method == 'POST':

        if not form.is_valid():
            render(request, 'enterprise/add_type.html', {'form': form})
        else:
            name = form.cleaned_data.get('name')

            t, created = Type.objects.get_or_create(name=name)

            t.save()
            return redirect('/enterprise/register')

    else:
        return render(request, 'enterprise/add_type.html', {'form': form})

def add_operation(request):
    form = OperationForm(request.POST)
    if request.method == 'POST':

        if not form.is_valid():
            render(request, 'enterprise/add_operation.html', {'form': form})
        else:
            name = form.cleaned_data.get('name')
            o, created = Operation.objects.get_or_create(name=name)
            o.save()
            return redirect('/enterprise/register')

    else:
        return render(request, 'enterprise/add_operation.html', {'form': form})


def add_material(request):
    form = MaterialForm(request.POST)
    if request.method == 'POST':

        if not form.is_valid():
            render(request, 'enterprise/add_material.html', {'form': form})
        else:
            name = form.cleaned_data.get('name')
            m, created = Material.objects.get_or_create(name=name)
            m.save()
            return redirect('/enterprise/register')

    else:
        return render(request, 'enterprise/add_material.html', {'form': form})


def add_prod(request):
    form = ProdForm(request.POST)
    if request.method == 'POST':

        if not form.is_valid():
            render(request, 'enterprise/add_prod.html', {'form': form})
        else:
            name = form.cleaned_data.get('name')

            t, created = Product.objects.get_or_create(name=name)

            t.save()
            return redirect('/enterprise/add_prod')

    else:
        return render(request, 'enterprise/add_prod.html', {'form': form})


def add_ass(request):
    form = AssForm(request.POST)
    if request.method == 'POST':

        if not form.is_valid():
            render(request, 'enterprise/add_ass.html', {'form': form})
        else:
            name = form.cleaned_data.get('name')

            t, created = Asset.objects.get_or_create(name=name)

            t.save()
            return redirect('/enterprise/add_ass')

    else:
        return render(request, 'enterprise/add_ass.html', {'form': form})
# Create your views here.

templates/base.html
{% load staticfiles %}

<!--
    This is the 'base' template, never loaded
    
    # 'home', 'user_home', 'search' extend this
-->

<!DOCTYPE html>
<html lang="en">

<head>
    <link href={% static 'css/base_styler.css' %} media="all" rel="stylesheet" type="text/css" />
    {% block css %}{% endblock %}
    <script type="text/javascript" src={% static 'js/jquery-2.1.1.js' %}></script>
    {% block js %}{% endblock %}
    <title>{% block title %}IndustryLogger{% endblock %}</title>
</head>

<body>
    <iframe id="notify_frame" class="outer_frame" src="" name="notify_frame"></iframe>
    <div id="wrapper"></div>
    <div class="container">
        <header class='header_top'>
        {% block header %}
            <a href="{% url 'home' %}"><h1 class='ilog'>IndustryLogger</h1></a>
        {% endblock %}
        {% if not hide_search %}
            <form id="search" action="{% url 'search' %}">
                <input type="text" id="search-text" name="q" placeholder="Search" required>
                <input type="submit" id="search-button" value="Go">
            </form>
        {% endif %}
        </header>

        <nav class='nav_top'>
            <ul class="ul_top">
            {% block menu_links %}
            {% endblock %}
            </ul>
        </nav>

        <section class='content'>
            <nav class='nav_content'>
                <ul class="ul_content">
                {% block menu_content_links %}
                {% endblock %}
                </ul>
            </nav>
            {% block content %}
            {% endblock %}
        </section>

        <hr class='hr_line' />

        <footer class='footer_bottom'>
            {% block footer %}
            {% endblock %}
            <p id="brandline"><i>version 0.01; under beta testing from <strong>12 Apr 2015</strong></i></p>
        </footer>
    </div>

    <script type="text/javascript">
        $(setDimensions);
        $(window).resize(setDimensions);
        function setDimensions () {
            var window_width = $(window).width();
            var window_height = $(window).height();
            var footer_height = $('.footer_bottom').outerHeight(true);
            var header_height = $('.header_top').outerHeight(true);

            $('.container').css({'min-height':window_height});
        }

        $(function(){
            $('.uls_home input, .uls_home select').attr({'required':'required'});
        });

        $('.framer').click(function(){
            var target = $(this).attr('target');
            var frame = $("iframe[name="+target+"]");
            var f_class = frame.attr('class');
            console.log(f_class);
            if (f_class == 'outer_frame'){
                $('#notify_frame').css({'z-index':'999'});
                $('#notify_frame').animate({'width':'58%','height':'60%','top':'90px','left':'18%'});
                $('#wrapper').css({'z-index':'900'});
                $('#wrapper').animate({'opacity':'0.5'});
                $('.close, #wrapper').click(function(){
                    $('#notify_frame').animate({'width':'0%','height':'0%','left':'50%'},cascade);
                    $('#wrapper').animate({'opacity':'0'},cascade);
                    function cascade(){
                        $(this).css({'z-index':'-100'});
                    };
                });
            }
            else if (f_class == 'inner_frame'){
                $('.profile_box').hide(1);
                $('#edit_frame').css({'z-index':'999'});
                $('#edit_frame').animate({'min-height':'400px'});
            }
        });
    </script>
    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-61433891-1', 'auto');
      ga('send', 'pageview');

    </script>
    <script type="text/javascript" src={% static 'js/frames.js' %}></script>
    {% block scripts %}
    {% endblock %}

</body>
</html>

templates/enterprises.html
{% extends "home.html" %}

{% block title %}Log in to i-Logger{% endblock %}

{% block menu_links %}
    <li class="link"><a href="{% url 'home' %}">Home</a></li>
    <li class="link"><a href="{% url 'logup' %}">Log Up</a></li>
{% endblock %}

{% block content %}
	{% for ent in enterprises %}
		<li class="name_enterprises">
			<a href="{% url 'enterprise:enterprise_profile' ent.slug %}">{{ ent|capfirst }}</a>
		</li>
	{% endfor %}
{% endblock %}

templates/frame.html
{% load staticfiles %}

<!--
    This is the 'frame' template, loaded only in iframes accross the site
    # 'notifications' extend this
-->

<!DOCTYPE html>
<html lang="en">

<head>
    <link href={% static 'css/frame_styler.css' %} media="all" rel="stylesheet" type="text/css" />
    {% block css %}{% endblock %}
    <script type="text/javascript" src={% static 'js/jquery-2.1.1.js' %}></script>
    {% block js %}{% endblock %}
    <title>{% block title %}the Industry Logger{% endblock %}</title>
</head>

<body>
    <div class="container">
        <header class='header_frame'>
            {% block header %}
            {% endblock %}
        </header>
        <section class='content'>
            {% block content %}
            {% endblock %}
        </section>
    </div>

    <script type="text/javascript">
        $(setDimensions);
        $(window).resize(setDimensions);

        function setDimensions () {
            var window_width = $(window).width();
            var window_height = $(window).height();
            var footer_height = $('.footer_bottom').outerHeight(true);
            var header_height = $('.header_top').outerHeight(true);
        }

    </script>
    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-61433891-1', 'auto');
      ga('send', 'pageview');

    </script>
    <script type="text/javascript" src={% static 'js/frames.js' %}></script>
    {% block scripts %}
    {% endblock %}

</body>
</html>

templates/home.html
{% extends "base.html" %}
{% load staticfiles %}

<!--
	This is the home page for a guest user.
-->

{% block css %}
	<link rel="stylesheet" type="text/css" href={% static 'css/home_styler.css' %}>
	<link rel="stylesheet" type="text/css" href={% static 'css/form_styler.css' %}>
{% endblock %}

{% block menu_links %}
    <li class="link"><a href="{% url 'logup' %}">Sign Up</a></li>
    <li class="link"><a href="{% url 'login' %}">Log In</a></li>
	<li class="link"><a href="{% url 'enterprise:register' %}">Register</a></li>
	
{% endblock %}

{% block content %}
	<section id='content_home'>
		<p>IndustryLogger.com is a website especially designed for small and medium scale Industries and the Industrialists as an open online community to connect with each other and with the large players of the market. Here you get a chance to create & Maintain your company's profile and a network of yourself and your Enterprise. It is a platform where you can discuss common problems, list your productsand promote your enterprise and its free to use. To avail all facilities,
			<h2><a href="{% url 'enterprise:register' %}">Register your Enterprise</a></h2>
		</p>
		<p>
			<h3><a href="{% url 'myuserprofile:enterprises' %}">Industries</a> which have joined the network already!</h3>
		</p>
		<p>
			<h3><a href="{% url 'myuserprofile:people' %}">People</a> who have joined the network already!</h3>
		</p>
	</section>
{% endblock %}

templates/login.html
{% extends "home.html" %}

{% block title %}Log in to i-Logger{% endblock %}

{% block menu_links %}
    <li class="link"><a href="{% url 'home' %}">Home</a></li>
    <li class="link"><a href="{% url 'logup' %}">Log Up</a></li>
{% endblock %}

{% block content %}
	<section id='content_login' class="contents">
		<header class="header_form">
			<h2>LOG IN</h2>
		</header>
		<form id="form_login" class="forms_home" action="{% url 'login' %}" method="POST" role="form" >
			<ul id="ul_login" class="uls_home">
				{{ form.as_ul }}
				{% csrf_token %}
				<li><input id="submit_login" class="submit_main" type="submit" value="LOG IN"></li>
			</ul>
		</form>
	</section>
{% endblock %}

templates/people.html
{% extends "home.html" %}

{% block title %}Log in to i-Logger{% endblock %}

{% block menu_links %}
    <li class="link"><a href="{% url 'home' %}">Home</a></li>
    <li class="link"><a href="{% url 'logup' %}">Log Up</a></li>
{% endblock %}

{% block content %}
	{% for my in myusers %}
		<li class="name_people">
			<a href="{% url 'myuserprofile:profile' my.slug %}">{{ my|capfirst }}</a>
		</li>
	{% endfor %}
{% endblock %}

templates/user_home.html
{% extends "base.html" %}
{% load imagekit %}
{% load staticfiles %}
{% load humanize %}

{% block css %}
	<link rel="stylesheet" type="text/css" href={% static 'css/home_styler.css' %}>
	<link rel="stylesheet" type="text/css" href={% static 'css/feed_styler.css' %}>
	<link rel="stylesheet" type="text/css" href={% static 'css/profile_styler.css' %}>
	{% block css_2 %}
	{% endblock %}
{% endblock %}

{% block menu_links %}
    <li class="link"><a class="a_menu" href="{% url 'home' %}">Home</a></li>
    {% if user.is_authenticated %}
    <li class="link"><a class="a_menu" href="{% url 'myuserprofile:profile' user.slug %}">My Profile</a></li>
    <li class="link"><a class="a_menu" href="{% url 'enterprise:enterprise_profile' user.enterprise.slug %}">Workplace</a></li>
    <li class="link"><a class="a_menu" href="{% url 'messages:inbox' %}">Messages</a></li>
    <li class="link"><a class="a_menu framer" target="notify_frame" href="{% url 'notifications' %}">Notifications</a></li>
	{% endif %}
    <li class="link right"><a href="{% url 'logout' %}">Log Out</a></li>
    {% if user.is_authenticated %}
    <li class="link_user">
		<a class="thumb_user" href="{% url 'myuserprofile:profile' user.slug %}"><img class="img_thumb" src="/images/{{ user.myuserprofile.get_image_thumbnail }}" alt="{{ user.get_full_name }}"></a>
		<div class="name"><a href="{% url 'myuserprofile:profile' user.slug %}">{{ user.get_full_name }}</a> | 
		<a href="{% url 'enterprise:enterprise_profile' user.enterprise.slug %}">{{ user.enterprise }}</a>
		</div>
	</li>
	{% endif %}
    <!--
    <li class="link right"><a class="a_menu" href="{% url 'myuserprofile:people' %}">People</a></li>
    <li class="link right"><a class="a_menu" href="{% url 'myuserprofile:enterprises' %}">Enterprises</a></li>
    -->
{% endblock %}

{% block menu_content_links %}
	<h3 class="ent_title"><a href=""></a></h3>
	<li class="link_content aj" class="a_menu">Feeds</li>
{% endblock %}

{% block content %}
	<section id="left_content">
	{% block left_content %}
		{% block left_menu %}
		{% endblock %}
		<aside id="people_list">
			<p class="list_head">People you may know...</p>
			<ul>
				{% for people in all_users %}
				<li class="list_object"><a href="{% url 'myuserprofile:profile' people.slug %}">
					<div class="list_object_name_2">{{ people }}<br>{{ people.enterprise }}</div>
					<img class="img_thumb_large" src="/images/{{ people.myuserprofile.get_image_thumbnail }}"></a>
				</li>
				{% endfor %}
			</ul>
		</aside>
	{% endblock %}
	</section>
		
	<section id="mid_content">
	{% block mid_content %}
		<form id="form_feed" role="form" action="{% url 'nodes:post' %}" method="POST">
			<textarea class="input_feed" form="form_feed" name="post" placeholder="Got something to discuss..?" required></textarea>
			<input class="submit_feed" type="submit" value="Feed">
			{% csrf_token %}
		</form>

	{% for node in feed_nodes %}
		<article class="feed_box" >
			<div class="feed_user">
				<a href="{% url 'myuserprofile:profile' node.myuser.slug %}">{{ node.myuser }}</a> | <a href="{% url 'enterprise:enterprise_profile' node.myuser.enterprise.slug %}">{{ node.myuser.enterprise }}</a>
				<div class="feed_date">{{ node.date }}</div>
			</div>
			<div class="feed_data">
				<div class="feed_body">{{ node.post }}</div>
				<div class="feed_response">
				{% for comments in node.get_comments %}
					<div class="comments">
						<div class="comment_user">
							{{ comments.myuser}} | {{ comments.myuser.enterprise}}
						</div>
						{{ comments.post }}
					</div>
				{% endfor %}
					<div class="comment_user">
							{{ user}} | {{ user.enterprise}}
					</div>
					<form class="form_comment" action="{% url 'nodes:comment' %}" method="POST">
						<textarea class="input_comment" name="post" placeholder="post a reply..." required></textarea>
						<input type="hidden" name="node" value="{{ node.pk }}">
						<input class="div_button" type="submit" value="Reply">
						{% csrf_token %}
					</form>
				</div>
			</div>
		</article>
	{% endfor %}
	{% endblock %}
	</section>

	<section id="right_content">
	{% block right_content %}
		<aside id="enterprise_list">
			<p class="list_head">Enterprises you may find interesting...</p>
			<ul>
				{% for enterprises in all_enterprises %}
				<li class="list_object"><a href="{% url 'enterprise:enterprise_profile' enterprises.slug %}">
					<img class="img_thumb_large" src="/images/{{ enterprises.enterpriseprofile.get_image_thumbnail }}">
					<div class="list_object_name_1">{{ enterprises }}</div>
					</a>
				</li>
				{% endfor %}
			</ul>

		</aside>
		<aside id="product_list">
			<p class="list_head">Products you may be looking for...</p>
			<ul>
				{% for products in all_products %}
				<li class=0 "list_object">
					<img class="img_thumb_large" src="{{ MEDIA_URL }}{{ products.get_product_image_thumbnail }}">
					<div class="list_object_name_1">{{ products }}</div>
				</li>
				{% endfor %}
			</ul>
		</aside>
	{% endblock %}
	</section>
	
{% endblock %}