enterprise/urls.py
from django.conf.urls import patterns, url
# from django.core.urlresolvers import reverse
from enterprise import views


urlpatterns = patterns('',
                       url(r'^register/$', views.register, name='register'),
                       url(r'^add_ass/$', 'enterprise.views.add_ass', name='add_ass'),
                       url(r'^add_prod/$', 'enterprise.views.add_prod', name='add_tprod'),

                       url(r'^add_product/$', 'enterprise.views.add_product', name='add_product'),
                       url(r'^add_asset/$', 'enterprise.views.add_asset', name='add_asset'),
                       url(r'^add_type/$', 'enterprise.views.add_type', name='add_type'),
                       url(r'^add_material/$', 'enterprise.views.add_material', name='add_material'),
                       url(r'^add_operation/$', 'enterprise.views.add_operation', name='add_operation'),
                       url(r'^edit/(?P<slug>[^/]+)/$', 'enterprise_profile.views.enterprise_profile_edit',
                           name='enterprise_profile_edit'),
                       url(r'^(?P<slug>[^/]+)/$', 'enterprise_profile.views.enterprise_profile',
                           name='enterprise_profile'),
                       url(r'^(?P<slug>[^/]+)/aj$', 'enterprise_profile.views.enterprise_profile_aj',
                           name='enterprise_profile_aj'),

                       url(r'^(?P<slug>[^/]+)/products/$', 'enterprise.views.product', name='product'),
                       url(r'^(?P<slug>[^/]+)/people/$', 'enterprise.views.people', name='people'),
                       url(r'^(?P<slug>[^/]+)/about/$', 'enterprise.views.about', name='about'),
                       url(r'^(?P<slug>[^/]+)/capability/$', 'enterprise.views.capability', name='capability'),

)


# urlpatterns += patterns('django.contrib.auth.views',
#         url(r'^login/$', 'login', { 'template_name': 'registration/login.html'}, name='login' ),
#         url(r'^logout/$', 'logout', { 'template_name': 'registration/my_account.html', 'next_page':reverse('index') }, name='logout' ),
# )

ilog_dev/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.views.generic import TemplateView
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = patterns('',

                       url(r'^admin/', include(admin.site.urls)), # admin interface

                       url(r'^$', 'myuserprofile.views.home', name='home'), # home page
                       url(r'^logup$', 'accounts.views.logup', name='logup'), # logup page
                       url(r'^login$', 'django.contrib.auth.views.login', {'template_name': 'login.html'}, name='login'),  # login page, redirects to 'home'
                       url(r'^logout$', 'django.contrib.auth.views.logout', {'next_page': 'login'}, name='logout'), # logout page, redirects to 'login'

                       url(r'^accounts/', include('accounts.urls', namespace='accounts')), # no use for now
                       url(r'^enterprise/', include('enterprise.urls', namespace='enterprise')),  # enterprise domain
                       url(r'^user/', include('myuserprofile.urls', namespace='myuserprofile')), # user domain
                       url(r'^nodes/', include('nodes.urls', namespace='nodes')),
                       url(r'^relationships/', include('relationships.urls', namespace='relationships')),

                       url(r'^messages/', include('message.urls', namespace='messages')),
                       url(r'^like/$', 'nodes.views.like', name='like'),
                       url(r'^search/$', 'search.views.search', name='search'),
                       # url(r'^search_adv/$', 'search.views.search_adv', name='search_adv'),

                       url(r'^images/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
                       url(r'^notifications/$', 'activities.views.notifications', name='notifications'),

                       url(r'^robots.txt/$', TemplateView.as_view(template_name='robots.txt')),

)   + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# urlpatterns += patterns('',
#                         (r'^media/(?P<path>.*)$', 'django.views.static.serve', {
#                          'document_root': settings.MEDIA_ROOT}))

# urlpatterns = patterns('',
# urlpatterns += staticfiles_urlpatterns()
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

nodes/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('nodes.views',
                       url(r'^$', 'nodes', name='nodes'),
                       url(r'^post/$', 'post', name='post'),
                       url(r'^comment/$', 'comment', name='comment'),
                       url(r'^like/$', 'like', name='like'),
                       # url(r'^post/$', 'post', name='post'),
                       # url(r'^unlike/$', 'unlike', name='unlike'),
#     url(r'^like/$', 'like', name='like'),
#     url(r'^comment/$', 'comment', name='comment'),
#     url(r'^load/$', 'load', name='load'),
#     url(r'^check/$', 'check', name='check'),
#     url(r'^load_new/$', 'load_new', name='load_new'),
#     url(r'^update/$', 'update', name='update'),
#     url(r'^track_comments/$', 'track_comments', name='track_comments'),
#     url(r'^remove/$', 'remove', name='remove_feed'),
#     url(r'^(\d+)/$', 'feed', name='feed'),
)

enterprise_profile/models.py
from django.db import models
from enterprise.models import Enterprise
# from nodes.models import Node
from accounts.models import MyUser
from django.db.models.signals import post_save
from django.db.models import signals
from imagekit.models import ProcessedImageField, ImageSpecField
from imagekit.processors import ResizeToFill


class EnterpriseProfile(models.Model):
    enterprise = models.OneToOneField(Enterprise)
    address = models. CharField(max_length=200, blank=True, null=True)
    contact = models.CharField(max_length=30, blank=True, null=True)
    website = models.URLField(max_length=255, null=True, blank=True)
    about = models.TextField(null=True, blank=True)
    capabilities = models.TextField(null=True, blank=True)
    people_detail = models.TextField(null=True, blank=True)
    product_intro = models.TextField(null=True, blank=True)
    image = ProcessedImageField(upload_to='enterprise/main',
                                processors=[ResizeToFill(1000, 1000)],
                                format='JPEG',
                                options={'quality': 60})
    image_thumbnail = ProcessedImageField(upload_to='enterprise/thumbnails',
                                          processors=[ResizeToFill(100, 100)],
                                          format='JPEG',
                                          options={'quality': 60})

    def __str__(self):
        return self.enterprise.enterprise

    def get_users(self):
        return self.enterprise.myuser_set.all()

    def get_products(self):
        return self.enterprise.products.all()

    def get_assets(self):
        return self.enterprise.assets.all()

    def get_enterprise_name(self):
        return self.enterprise.name

    # def get_nodes(self):
    #     a = self.enterprise.myuser.all()
    #     for ab in a:
    #         c = ab.node_set.all()
    #     return c

    def get_image(self):
        default = 'enterprise/main/enterprise.jpg'
        if self.image:
            return self.image
        else:
            return default

    def get_image_thumbnail(self):
        default = 'enterprise/thumbnails/enterprise.jpg'
        if self.image_thumbnail:
            return self.image_thumbnail
        else:
            return default


# from imagekit import ImageSpec, register
# class Thumbnail(ImageSpec):
#     processors = [ResizeToFill(100, 50)]
#     format = 'JPEG'
#     options = {'quality': 60}
#
# register.generator('myapp:thumbnail', Thumbnail)


# def save(self, *args, **kwargs):
#         # if not self.id:                  # Newly created object, so set slug
#         #     self.slug = slugify(self.enterprise).__str__()
#     super(EnterpriseProfile, self).save(*args, **kwargs)


def create_enterprise_profile(sender, instance, created, **kwargs):
    """Create ModelB for every new ModelA."""
    if created:
        EnterpriseProfile.objects.create(enterprise=instance)

signals.post_save.connect(create_enterprise_profile, sender=Enterprise, weak=False,
                          dispatch_uid='models.create_enterprise_profile')

# post_save.connect(create_enterprise_profile, sender=MyUser)
# post_save.connect(save_enterprise_profile, sender=MyUser)


# Create your models here.

# def create_enterprise_profile()

enterprise_profile/forms.py
from django import forms
from enterprise_profile.models import EnterpriseProfile


class EnterpriseProfileForm(forms.ModelForm):
    address = forms.CharField(widget=forms.Textarea, max_length=200, required=False)
    contact = forms.CharField(widget=forms.Textarea, max_length=50, required=False)
    about = forms.CharField(widget=forms.Textarea, max_length=5000, required=False)
    capabilities = forms.CharField(widget=forms.Textarea, max_length=5000, required=False)
    people_detail = forms.CharField(widget=forms.Textarea, max_length=5000, required=False)
    product_intro = forms.CharField(widget=forms.Textarea, max_length=5000, required=False)
    website = forms.CharField(required=False)
    image = forms.ImageField(required=False)

    class Meta:
        model = EnterpriseProfile
        exclude = ['enterprise']
        fields = ['address', 'contact', 'about', 'website', 'image', 'capabilities', 'people_detail', 'product_intro']

enterprise_profile/views.py
from django.shortcuts import render, redirect, get_object_or_404, HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from enterprise_profile.forms import EnterpriseProfileForm
from enterprise_profile.models import EnterpriseProfile
from enterprise.models import Enterprise
from accounts.models import MyUser
from nodes.models import Node
from django.core.urlresolvers import reverse


@login_required
def enterprise_profile_edit(request, slug):
    enterprise = request.user.enterprise
    page_enterprise = get_object_or_404(Enterprise, slug=slug)    
    if request.method == 'POST':
        
        form = EnterpriseProfileForm(request.POST, request.FILES)
        print(form.errors)
        if form.is_valid():
            image = form.cleaned_data.get('image')
            about = form.cleaned_data.get('about')
            contact = form.cleaned_data.get('contact')
            website = form.cleaned_data.get('website')
            address = form.cleaned_data.get('address')
            capabilities = form.cleaned_data.get('capabilities')
            people_detail = form.cleaned_data.get('people_detail')
            product_intro = form.cleaned_data.get('product_intro')

            ep = EnterpriseProfile.objects.get(enterprise=enterprise)

            ep.image = image
            ep.image_thumbnail = image
            ep.address = address
            ep.contact = contact
            ep.about = about
            ep.website = website
            ep.capabilities = capabilities
            ep.people_detail = people_detail
            ep.product_intro = product_intro
            ep.save()

            myuser = request.user
            edit_post = u'{0} from {1} has edited the enterprise profile.'.format(myuser.first_name, myuser.enterprise)
            node = Node(myuser=myuser, post=edit_post)
            node.save()

            myuser.myuserprofile.notify_edited(enterprise=enterprise, node=node)

            return redirect('/enterprise/'+ slug)
        else:
            print('wtf')

    else:
        form = EnterpriseProfileForm(instance=enterprise, initial={
            'about': enterprise.enterpriseprofile.about,
            'address': enterprise.enterpriseprofile.address,
            'contact': enterprise.enterpriseprofile.contact,
            'website': enterprise.enterpriseprofile.website,
            'image': enterprise.enterpriseprofile.get_image,
            'capabilities': enterprise.enterpriseprofile.capabilities,
            'people_detail': enterprise.enterpriseprofile.people_detail,
            'product_intro': enterprise.enterpriseprofile.product_intro,
            })
    return render(request, 'enterprise_profile/enterprise_profile_edit.html', {'form':form,'page_enterprise':page_enterprise})


def enterprise_profile(request, slug):
    # slug = request.user.slug
    myuser = request.user
    page_enterprise = get_object_or_404(Enterprise, slug=slug)
    members = MyUser.objects.filter(enterprise=page_enterprise)

    return render(request, 'enterprise_profile/enterprise_profile.html', {
        'page_enterprise': page_enterprise,
        'profile':EnterpriseProfile.objects.get(enterprise=page_enterprise),
        'members': members,
        'slug': slug,
        'myuser': myuser
        })
    # return HttpResponseRedirect(reverse('enterprise:enterprise_profile'),  {
    #     'page_enterprise': page_enterprise,
    #     'members': members,
    #
    #     'args': slug,
    #     }, args=(slug,))

def enterprise_profile_aj(request, slug):
    # slug = request.user.slug
    myuser = request.user
    page_enterprise = get_object_or_404(Enterprise, slug=slug)
    members = MyUser.objects.filter(enterprise=page_enterprise)

    return render(request, 'enterprise_profile/enterprise_profile_aj.html', {
        'page_enterprise': page_enterprise,
        'profile':EnterpriseProfile.objects.get(enterprise=page_enterprise),
        'members': members,
        'slug': slug,
        'myuser': myuser
        })

# Create your views here.

templates/enterprise_profile/enterprise_profile.html
{% extends "user_home.html" %}
{% load imagekit %}
{% load staticfiles %}

{% block css_2 %}
	<link rel="stylesheet" type="text/css" href={% static 'css/profile_styler.css' %}>
	<link rel="stylesheet" type="text/css" href={% static 'css/form_styler.css' %}>
	{% block css_3 %}
	{% endblock %}
{% endblock %}

{% block menu_content_links %}
	<h3 class="ent_title"><a href="{% url 'enterprise:enterprise_profile' page_enterprise.slug %}">{{ page_enterprise }}</a></h3>
	<a href="{% url 'enterprise:enterprise_profile' page_enterprise.slug %}"><li class="link_content">About</li></a>
    <li class="link_content aj" data-link="{% url 'enterprise:product' page_enterprise.slug %}">Products</li>
    <li class="link_content aj" data-link="{% url 'enterprise:capability' page_enterprise.slug %}">Capabilities</li>
    <li class="link_content aj" data-link="{% url 'enterprise:people' page_enterprise.slug %}">People</li>
    <li class="link_content aj">Connections</li>
{% endblock %}

{% block left_content %}
	<div id="left_ent">
		<img id="ent_img" src="/images/{{ profile.get_image }}" alt="{{ page_enterprise }}">
	</div>
	<dl class="left_info">
		<div class="info_box">
			<dt class="info_name">Type :</dt>
			{% for type in page_enterprise.types.all %}
			<dd class="info_data">{{ type }}</dd>
			{% endfor %}
		</div>
		<div class="info_box">
			<dt class="info_name">Contact :</dt>
			<dd class="info_data">{{ profile.contact }}</dd>
		</div>
		<div class="info_box">
			<dt class="info_name">Website :</dt>
			<dd class="info_data"><a href="{{ profile.website }}" >{{ profile.website }}</a></dd>
		</div>
	</dl>
{% endblock %}

{% block mid_content %}
	<section id="mid_content_box">
{% ifequal myuser.enterprise page_enterprise %}
	<iframe id="edit_frame" class="inner_frame" name="edit_frame" src=""></iframe>
{% endifequal %}
		<dl class="profile_box">
		{% ifequal myuser.enterprise page_enterprise %}
			<a class="pop_link_left framer" href="{% url 'enterprise:enterprise_profile_edit' page_enterprise.slug %}" target="edit_frame">edit</a>
		{% endifequal %}
			<div class="info_box">
			<dt class="info_name">About :</dt>
			<dd class="info_data wide">{{ profile.about }}</dd>
			</div>
			<div class="info_box half">
			<dt class="info_name">Address :</dt>
			<dd class="info_data wide">{{ profile.address }}</dd>
			</div>
		</dl>
	</section>
{% endblock %}

{% block scripts %}
	<script type="text/javascript">
		$('.aj').click(function(){
			var $this = $(this);
			var url = $(this).data('link');
			console.log($('#mid_content_box').text());
			$('#mid_content_box').load(url);
			
			function hido(){
				var hide = $('.profile').find('.hidden');
				var hide_this = hide.data('hide');
				$('.'+hide_this).text('');
			}
		});
	</script>
{% endblock %}

templates/enterprise_profile/enterprise_profile_aj.html
{% ifequal myuser.enterprise page_enterprise %}
		<iframe id="edit_frame" class="inner_frame" name="edit_frame" src=""></iframe>
	{% endifequal %}
		<dl class="profile_box">
		{% ifequal myuser.enterprise page_enterprise %}
			<a class="pop_link_left framer" href="{% url 'enterprise:enterprise_profile_edit' %}" target="edit_frame">edit</a>
		{% endifequal %}
			<div class="info_box">
			<dt class="info_name">About :</dt>
			<dd class="info_data wide">{{ profile.about }}</dd>
			</div>
			<div class="info_box half">
			<dt class="info_name">Address :</dt>
			<dd class="info_data wide">{{ profile.address }}</dd>
			</div>
		</dl>

<script type="text/javascript">
	$('.framer').click(function(){
            var target = $(this).attr('target');
            var frame = $("iframe[name="+target+"]");
            var f_class = frame.attr('class');
            console.log(f_class);
            if (f_class == 'outer_frame'){
                $('#notify_frame').css({'z-index':'999'});
                $('#notify_frame').animate({'width':'58%','height':'60%','top':'90px','left':'18%'});
                $('#wrapper').css({'z-index':'900'});
                $('#wrapper').animate({'opacity':'0.5'});
                $('.close, #wrapper').click(function(){
                    $('#notify_frame').animate({'width':'0%','height':'0%','left':'50%'},cascade);
                    $('#wrapper').animate({'opacity':'0'},cascade);
                    function cascade(){
                        $(this).css({'z-index':'-100'});
                    };
                });
            }
            else if (f_class == 'inner_frame'){
                $('.profile_box').hide(1);
                $('#edit_frame').css({'z-index':'999'});
                $('#edit_frame').animate({'width':'90%','min-height':'400px','left':'5%'});
            }
        });
</script>

templates/enterprise_profile/enterprise_profile_edit.html
{% extends 'frame.html' %}
{% load staticfiles %}

{% block css %}
	<link href={% static 'css/form_styler.css' %} media="all" rel="stylesheet" type="text/css" />
{% endblock %}

{% block content %}
<section id="content_enterprise_profile_edit">
	<header class="header_form">
		<h2>Update your enterprise info . . .</h2>
	</header>
	<form class="" enctype="multipart/form-data" action="{% url 'enterprise:enterprise_profile_edit' page_enterprise.slug %}" target='_parent' method="POST" role="form" >
		<input type="submit" value="save" class="pop_link_left">
		<ul class="form_edit">
			{{ form.as_ul }}
			{% csrf_token %}
		</ul>
	</form>
</section>
{% endblock %}

templates/enterprise_profile/enterprise_profile_edit_old.html
{% extends "user_home.html" %}
{% load imagekit %}
{% load staticfiles %}

{% block css_2 %}
	<link rel="stylesheet" type="text/css" href={% static 'css/profile_styler.css' %}>
	<link rel="stylesheet" type="text/css" href={% static 'css/form_styler.css' %}>
{% endblock %}

{% block left_content %}
	<div id="left_ent">
		<h3 class="ent_title"><a href="">{{ page_enterprise }}</a></h3>
		<img id="ent_img" src="/images/{{ profile.get_image }}" alt="{{ page_enterprise }}">
	</div>
	<dl class="left_info">
		<div class="info_box">
			<dt class="info_name">Type :</dt>
			{% for type in page_enterprise.types.all %}
			<dd class="info_data">{{ type }}</dd>
			{% endfor %}
		</div>
		<div class="info_box">
			<dt class="info_name">Contact :</dt>
			<dd class="info_data">{{ profile.contact }}</dd>
		</div>
		<div class="info_box">
			<dt class="info_name">Website :</dt>
			<dd class="info_data">{{ profile.website }}</dd>
		</div>
	</dl>
{% endblock %}

{% block mid_content %}
	<section id="content_enterprise_profile_edit">
		<header class="header_form">
			<h2>Update your enterprise info . . .</h2>
		</header>
		<form enctype="multipart/form-data" action="" method="POST" role="form" >
			<ul class="form_edit">
			<li><input type="submit" value="save" class="pop_link_left">
			</li>
				{{ form.as_ul }}
				{% csrf_token %}
				{{ form.errors }}{{ form.non_field_errors }}
				<li><input type="submit" value="save" class="pop_link_left">
			</li>				
			</ul>
		</form>
	</section>
{% endblock %}