enterprise/urls.py
from django.conf.urls import patterns, url
# from django.core.urlresolvers import reverse
from enterprise import views


urlpatterns = patterns('',
                       url(r'^register/$', views.register, name='register'),
                       url(r'^add_ass/$', 'enterprise.views.add_ass', name='add_ass'),
                       url(r'^add_prod/$', 'enterprise.views.add_prod', name='add_tprod'),

                       url(r'^add_product/$', 'enterprise.views.add_product', name='add_product'),
                       url(r'^add_asset/$', 'enterprise.views.add_asset', name='add_asset'),
                       url(r'^add_type/$', 'enterprise.views.add_type', name='add_type'),
                       url(r'^add_material/$', 'enterprise.views.add_material', name='add_material'),
                       url(r'^add_operation/$', 'enterprise.views.add_operation', name='add_operation'),
                       url(r'^edit/(?P<slug>[^/]+)/$', 'enterprise_profile.views.enterprise_profile_edit',
                           name='enterprise_profile_edit'),
                       url(r'^(?P<slug>[^/]+)/$', 'enterprise_profile.views.enterprise_profile',
                           name='enterprise_profile'),
                       url(r'^(?P<slug>[^/]+)/aj$', 'enterprise_profile.views.enterprise_profile_aj',
                           name='enterprise_profile_aj'),

                       url(r'^(?P<slug>[^/]+)/products/$', 'enterprise.views.product', name='product'),
                       url(r'^(?P<slug>[^/]+)/people/$', 'enterprise.views.people', name='people'),
                       url(r'^(?P<slug>[^/]+)/about/$', 'enterprise.views.about', name='about'),
                       url(r'^(?P<slug>[^/]+)/capability/$', 'enterprise.views.capability', name='capability'),

)


# urlpatterns += patterns('django.contrib.auth.views',
#         url(r'^login/$', 'login', { 'template_name': 'registration/login.html'}, name='login' ),
#         url(r'^logout/$', 'logout', { 'template_name': 'registration/my_account.html', 'next_page':reverse('index') }, name='logout' ),
# )

ilog_dev/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.views.generic import TemplateView
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = patterns('',

                       url(r'^admin/', include(admin.site.urls)), # admin interface

                       url(r'^$', 'myuserprofile.views.home', name='home'), # home page
                       url(r'^logup$', 'accounts.views.logup', name='logup'), # logup page
                       url(r'^login$', 'django.contrib.auth.views.login', {'template_name': 'login.html'}, name='login'),  # login page, redirects to 'home'
                       url(r'^logout$', 'django.contrib.auth.views.logout', {'next_page': 'login'}, name='logout'), # logout page, redirects to 'login'

                       url(r'^accounts/', include('accounts.urls', namespace='accounts')), # no use for now
                       url(r'^enterprise/', include('enterprise.urls', namespace='enterprise')),  # enterprise domain
                       url(r'^user/', include('myuserprofile.urls', namespace='myuserprofile')), # user domain
                       url(r'^nodes/', include('nodes.urls', namespace='nodes')),
                       url(r'^relationships/', include('relationships.urls', namespace='relationships')),

                       url(r'^messages/', include('message.urls', namespace='messages')),
                       url(r'^like/$', 'nodes.views.like', name='like'),
                       url(r'^search/$', 'search.views.search', name='search'),
                       # url(r'^search_adv/$', 'search.views.search_adv', name='search_adv'),

                       url(r'^images/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
                       url(r'^notifications/$', 'activities.views.notifications', name='notifications'),

                       url(r'^robots.txt/$', TemplateView.as_view(template_name='robots.txt')),

)   + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# urlpatterns += patterns('',
#                         (r'^media/(?P<path>.*)$', 'django.views.static.serve', {
#                          'document_root': settings.MEDIA_ROOT}))

# urlpatterns = patterns('',
# urlpatterns += staticfiles_urlpatterns()
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myuserprofile/urls.py
from django.conf.urls import patterns, url, include
from django.core.urlresolvers import reverse
from myuserprofile import views

urlpatterns = patterns('',
                       # url(r'^follow/$', views.follow, name='follow'),
                       # url(r'^unfollow/$', views.unfollow, name='unfollow'),
                       # url(r'^block/$', views.block, name='block'),
                       # url(r'^unblock/$', views.unblock, name='unblock'),
                       url(r'^edit/$', 'myuserprofile.views.profile_edit', name='profile_edit'),
                       url(r'^enterprises/$', 'myuserprofile.views.enterprises', name='enterprises'),
                       url(r'^people/$', 'myuserprofile.views.people', name='people'),
                       url(r'^skillset/$', 'myuserprofile.views.skillset', name='skillset'),
                       url(r'^relationships', include('relationships.urls', namespace='relationships')),
                       url(r'^(?P<slug>[^/]+)/$', 'myuserprofile.views.profile', name='profile'),
                       url(r'^(?P<slug>[^/]+)/$', 'myuserprofile.views.activity', name='activity'),



                       # url(r'^(?P<slug>[^/]+)/follow/$', 'myuserprofile.views.follow', name='follow'),
                       # url(r'^(?P<slug>[^/]+)/unfollow/$', 'myuserprofile.views.unfollow', name='unfollow'),
)

nodes/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('nodes.views',
                       url(r'^$', 'nodes', name='nodes'),
                       url(r'^post/$', 'post', name='post'),
                       url(r'^comment/$', 'comment', name='comment'),
                       url(r'^like/$', 'like', name='like'),
                       # url(r'^post/$', 'post', name='post'),
                       # url(r'^unlike/$', 'unlike', name='unlike'),
#     url(r'^like/$', 'like', name='like'),
#     url(r'^comment/$', 'comment', name='comment'),
#     url(r'^load/$', 'load', name='load'),
#     url(r'^check/$', 'check', name='check'),
#     url(r'^load_new/$', 'load_new', name='load_new'),
#     url(r'^update/$', 'update', name='update'),
#     url(r'^track_comments/$', 'track_comments', name='track_comments'),
#     url(r'^remove/$', 'remove', name='remove_feed'),
#     url(r'^(\d+)/$', 'feed', name='feed'),
)

myuserprofile/forms.py
from django import forms
from myuserprofile.models import MyUserProfile
from enterprise.models import Operation


class ProfileForm(forms.ModelForm):
    image = forms.ImageField()
    GenderChoices = (('M', 'Male'), ('F', 'Female'),)
    gender = forms.ChoiceField(choices=GenderChoices, widget=forms.Select(attrs={'class':'regDropDown'}))
    job_position = forms.CharField(max_length=255, required=False)
    experience = forms.CharField(widget=forms.Textarea, max_length=5000, required=False)
    summary = forms.CharField(widget=forms.Textarea, max_length=5000, required=False)
    skillset = forms.ModelMultipleChoiceField(queryset=Operation.objects.all(), required=False)


    class Meta:
        model = MyUserProfile
        exclude = ['follows', 'score', 'myuser']
        fields = ['image', 'gender', 'job_position', 'experience', 'summary']

myuserprofile/views.py
from django.shortcuts import render, redirect, get_object_or_404, HttpResponseRedirect, render_to_response
from enterprise.models import Enterprise, EnterpriseProduct
from accounts.models import MyUser
from django.contrib.auth.decorators import login_required
# from nodes.views import nodes
from nodes.models import Node
from django.core.paginator import Paginator
from myuserprofile.forms import ProfileForm
from myuserprofile.models import MyUserProfile, Relationship
from django.core.urlresolvers import reverse
from PIL import Image
from django.template import RequestContext


NODES_NUM_PAGES = 18


def home(request):
    if request.user.is_authenticated():
        all_feed_nodes = Node.get_feeds()
        paginator = Paginator(all_feed_nodes, NODES_NUM_PAGES)
        feed_nodes = paginator.page(1)
        comment_nodes = Node.objects.filter(myuser=request.user, category='C')
        all_users = MyUser.objects.all().order_by('-last_login')[:10]
        all_enterprises = Enterprise.objects.all()[:4]
        all_products = EnterpriseProduct.objects.all()[:4]
        c = {'user': request.user,
             'profile': MyUserProfile.objects.get(myuser=request.user),
             'feed_nodes': feed_nodes,
             'page': 2,
             'all_users': all_users,
             'all_enterprises': all_enterprises,
             'all_products':all_products}
        return render_to_response('user_home.html', c, context_instance=RequestContext(request))
    else:
        return render(request, 'home.html')

def activity(request):
    if request.user.is_authenticated():
        feed_nodes = Node.get_feeds()
        comment_nodes = Node.objects.filter(myuser=request.user, category='C')
        c = {'user': request.user,
             'profile': MyUserProfile.objects.get(myuser=request.user),
             'feed_nodes': feed_nodes}
        return render_to_response('user_home.html', c)
    else:
        return render(request, 'home.html')

FEEDS_NUM_PAGES=8
# @login_required
def enterprises(request):
    myusers = MyUser.objects.all()
    enterprises = Enterprise.objects.all().order_by('-id')
    return render(request, 'enterprises.html', {'enterprises':enterprises})
# @login_required
def people(request):
    myusers = MyUser.objects.all().order_by('-id')
    enterprises = Enterprise.objects.all()
    return render(request, 'people.html', {'myusers': myusers})

# @login_required
def profile(request, slug):
    context = RequestContext(request)
    page_user = get_object_or_404(MyUser, slug=slug)
    user = request.user
    page_user_profile = page_user.myuserprofile
    all_feeds = Node.get_feeds().filter(myuser=page_user)
    # paginator = Paginator(all_feeds, FEEDS_NUM_PAGES)
    # feeds = paginator.page(1)
    # from_feed = -1
    # if feeds:
    #     from_feed = feeds[0].id
    #feed_nodes = Node.objects.filter(myuser=request.user, category='F')
    skillset = page_user_profile.skillset.all()

    try:
        relationship_status = Relationship.objects.get(to_user_id=page_user.myuserprofile.id,
                                                       from_user_id=request.user.myuserprofile.id).status
    except:
        relationship_status = 'none'
    # relationship_status = Relationship.objects.get(to_user_id=page_user.myuserprofile.id,
    #                                                from_user_id=request.user.myuserprofile.id).status
    data={'skillset': skillset,
          'relationship_status': relationship_status,
          'feeds': all_feeds,
          'user': user,
          'page_user': page_user,
          'page_user_profile': page_user_profile,
        #  'nodes': feed_nodes
    }
    return render_to_response('myuserprofile/profile.html', data, context_instance=context)

def skillset(request, slug):
    context = RequestContext(request)
    page_user = get_object_or_404(MyUser, slug=slug)
    page_user_profile = page_user.myuserprofile
    skillset = page_user_profile.skillset.all()
    data={'skillset':skillset}
    return render_to_response('myuserprofile/skillset.html', data, context_instance=context)
#ye master me dikhega
@login_required
def profile_edit(request):
    myuser = request.user
    mup = MyUserProfile.objects.get(myuser=myuser)
    if request.method == 'POST':

        form = ProfileForm(request.POST, request.FILES)
        # print(form.errors)

        if form.is_valid():

            image = form.cleaned_data.get('image')
            gender = form.cleaned_data.get('gender')
            experience = form.cleaned_data.get('experience')
            summary = form.cleaned_data.get('summary')
            job_position = form.cleaned_data.get('job_position')
            skillset = form.cleaned_data.get('skillset')

            mup.image = image
            mup.image_thumbnail = image
            mup.gender = gender
            mup.summary = summary
            mup.experience = experience
            mup.job_position = job_position
            mup.skillset = skillset
            mup.save()

            return redirect('/user/'+myuser.slug)

    else:
        form = ProfileForm(instance=myuser, initial={
            'job_position': myuser.myuserprofile.job_position,
            'summary': myuser.myuserprofile.summary,
            'gender': myuser.myuserprofile.gender,
            'experience': myuser.myuserprofile.experience,
            'image': myuser.myuserprofile.image,
            'skillset': mup.skillset.all()

            })
    return render(request, 'myuserprofile/profile_edit.html', {'form': form})

@login_required
def follow(request):
    myuser = request.user
    # to_us = MyUser.objects.get(id=request.POST['to_user'])
    if request.method == 'POST':
        to_use = MyUser.objects.get(id=request.POST['to_user'])
        to_user = MyUser.objects.get(id=request.POST['to_user']).myuserprofile
        rel, created = Relationship.objects.get_or_create(
            from_user=myuser.myuserprofile,
            to_user=to_user,
            defaults={'status': 'F'}
        )
        if created:
            follow_post = u'{0}from {1} is now following you.'.format(myuser.first_name, myuser.enterprise)

            node = Node(myuser=myuser, post=follow_post, is_active=False)
            node.save()

            myuser.myuserprofile.notify_followed(user=to_use, node=node)

        if not created:
            rel.status = 'F'
            rel.save()

        return HttpResponseRedirect('/user/'+to_use.slug)
    else:
        return HttpResponseRedirect('/')

@login_required()
def block(request):
    if request.method == 'POST':
        to_user = MyUser.objects.get(id=request.POST['to_user'])
        rel, created = Relationship.objects.get_or_create(
            from_user=request.user.id,
            to_user=to_user,
            defaults={'status': 'blocked'}
        )

        if not created:
            rel.status = 'blocked'
            rel.save()
        # if request.is_ajax():
        #   return HttpResponse(status=200)
        # else:
        #   return HttpResponseRedirect(reverse('said_user:profile', kwargs={'username': to_user.username}))
    else:
        return HttpResponseRedirect(reverse('main:home'))

@login_required()
def unfollow(request):
    if request.method == 'POST':
        to_use = MyUser.objects.get(id=request.POST['to_user'])
        to_user = MyUser.objects.get(id=request.POST['to_user']).myuserprofile

        Relationship.objects.filter(
            from_user=request.user.myuserprofile,
            to_user=to_user).update(status='N')

        # if request.is_ajax():
        #   return HttpResponse(status=200)
        # else:
        #   return HttpResponseRedirect(reverse('said_user:profile', kwargs={'username': to_user.username}))
        print('why')
        return HttpResponseRedirect('/user/'+to_use.slug)

    else:

        return HttpResponseRedirect('/')

@login_required()
def unblock(request):

    if request.method == 'POST':
        to_user = MyUser.objects.get(id=request.POST['to_user'])

        rel = Relationship.objects.filter(
            from_user=request.user,
            to_user=to_user).update(status='none')

        # if request.is_ajax():
        #   return HttpResponse(status=200)
        # else:
        #   return HttpResponseRedirect(reverse('said_user:profile', kwargs={'username': to_user.username}))

    else:
        return HttpResponseRedirect(reverse('main:home'))

# Create your views here.

templates/myuserprofile/cover.html
{% extends 'base.html' %}
{% load i18n %}

{% block head %}
  <link href="{{ STATIC_URL }}css/cover.css" rel="stylesheet">
{% endblock head %}

{% block body %}
  <a href="https://github.com/vitorfs/bootcamp"><img style="position: absolute; top: 0; right: 0; border: 0;" src="https://camo.githubusercontent.com/e7bbb0521b397edbd5fe43e7f760759336b5e05f/68747470733a2f2f73332e616d617a6f6e6177732e636f6d2f6769746875622f726962626f6e732f666f726b6d655f72696768745f677265656e5f3030373230302e706e67" alt="Fork me on GitHub" data-canonical-src="https://s3.amazonaws.com/github/ribbons/forkme_right_green_007200.png"></a>
  <div class="cover">
    <h1 class="logo">Bootcamp</h1>
    {% if form.non_field_errors %}
      {% for error in form.non_field_errors %}
        <div class="alert alert-danger alert-dismissable">
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
          {{ error }}
        </div>
      {% endfor %}
    {% endif %}
    <div class="login">
      <h2>{% trans 'Log in' %}</h2>
      <form method="post" action="{% url 'login' %}" role="form">
        {% csrf_token %}
        <div class="form-group{% if form.username.errors %} has-error{% endif %}">
          <label for="username">{% trans 'Username' %}</label>
          <input type="text" class="form-control" id="username" name="username">
          {% for error in form.username.errors %}
            <label class="control-label">{{ error }}</label>
          {% endfor %}
        </div>
        <div class="form-group{% if form.password.errors %} has-error{% endif %}">
          <label for="password">{% trans 'Password' %}</label>
          <input type="password" class="form-control" id="password" name="password">
          {% for error in form.password.errors %}
            <label class="control-label">{{ error }}</label>
          {% endfor %}
        </div>
        <div class="form-group">
          <button type="submit" class="btn btn-default">{% trans 'Log in' %}</button>
          <a href="{% url 'signup' %}" class="btn btn-link">{% trans 'Sign up for Bootcamp' %}</a>
        </div>
      </form>
    </div>
  </div>
{% endblock body %}

templates/myuserprofile/network.html
{% extends 'user_home.html' %}

{% block left_menu %}

{% endblock %}

{% block mid_content %}
	<h2>Enterprises in the network</h2>
        <ul class="list">
        {% for enterprise in enterprises %}
            <li class="name_enterprise">
                <a href="{% url 'enterprise:enterprise_profile' enterprise.slug %}">{{ enterprise|capfirst }}</a>
            </li>
        {% endfor %}
        </ul>
		
    <h2>People in the network</h2>
        <ul class="list">
        {% for myuser in myusers %}
            <li class="name_people">
                <a href="{% url 'myuserprofile:profile' myuser.slug %}">{{ myuser }}</a>
            </li>
        {% endfor %}
        </ul>
{% endblock %}

templates/myuserprofile/password.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}{% trans 'Account Settings' %}{% endblock %}

{% block main %}
  <div class="page-header">
    <h1>{% trans 'Account Settings' %}</h1>
  </div>
  <div class="row" style="margin-top: 2em">
    <div class="col-md-3">
      {% include 'core/partial_settings_menu.html' with active='password' %}
    </div>
    <div class="col-md-9">
      {% if messages %}
        {% for message in messages %}
          <div class="alert alert-success alert-dismissable">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            {{ message }}
          </div>
        {% endfor %}
      {% endif %}
      <h3 style="margin-top: 0">{% trans 'Change Password' %}</h3>
      <form role="form" class="form-horizontal" method="post" action="{% url 'password' %}">
        {% csrf_token %}
        {{ form.id }}
        {% for field in form.visible_fields %}
          <div class="form-group{% if field.errors %} has-error{% endif %}">
            <label for="{{ field.label }}" class="col-sm-3 control-label">{{ field.label }}</label>
            <div class="col-sm-9">
              {{ field }}
              {% if field.help_text %}
                <span class="help-block">{{ field.help_text }}</span>
              {% endif %}
              {% for error in field.errors %}
                <label class="control-label">{{ error }}</label>
              {% endfor %}
            </div>
          </div>
        {% endfor %}
        <div class="form-group">
          <div class="col-sm-offset-3 col-sm-9">
            <button type="submit" class="btn btn-primary">{% trans 'Save' %}</button>
          </div>
        </div>
      </form>
    </div>
  </div>
{% endblock main %}

templates/myuserprofile/picture.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}{% trans 'Account Settings' %}{% endblock %}

{% block head %}
  <link href="{{ STATIC_URL }}css/jquery.Jcrop.min.css" rel="stylesheet">
  <script src="{{ STATIC_URL }}js/jquery.Jcrop.min.js"></script>
  <script src="{{ STATIC_URL }}js/picture.js"></script>
{% endblock head %}

{% block main %}
  <div class="page-header">
    <h1>{% trans 'Account Settings' %}</h1>
  </div>
  <div class="row" style="margin-top: 2em">
    <div class="col-md-3">
      {% include 'core/partial_settings_menu.html' with active='picture' %}
    </div>
    <div class="col-md-9">
      {% if messages %}
        {% for message in messages %}
          <div class="alert alert-success alert-dismissable">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            {{ message }}
          </div>
        {% endfor %}
      {% endif %}
      <h3 style="margin-top: 0">{% trans 'Change Picture' %}</h3>
      <img src="{{ user.profile.get_picture }}" style="width: 150px; border-radius: 5px; margin-bottom: 1em;">
      <form enctype="multipart/form-data" method="post" action="{% url 'upload_picture' %}" id="picture-upload-form">
        {% csrf_token %}
        <input type="file" name="picture" style="display: none">
        <button type="button" class="btn btn-default" id="btn-upload-picture">{% trans 'Upload new picture' %}</button>
      </form>

      {% if uploaded_picture %}
        <form method="post" action="{% url 'save_uploaded_picture' %}">
          {% csrf_token %}
          <div class="modal fade" id="modal-upload-picture">
            <div class="modal-dialog">
              <div class="modal-content">
                <div class="modal-header">
                  <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                  <h4 class="modal-title">{% trans 'Crop Picture' %}</h4>
                </div>
                <div class="modal-body">
                  <div class="selected-picture">
                    <p>{% trans 'Crop the profile picture and then click on the' %} <strong>{% trans 'Save Picture' %}</strong> {% trans 'button' %}</p>
                    <img src="{{ MEDIA_URL }}profile_pictures/{{ user.username }}_tmp.jpg?_={% now 'U' %}" id="crop-picture">
                    <input type="hidden" id="x" name="x" />
                    <input type="hidden" id="y" name="y" />
                    <input type="hidden" id="w" name="w" />
                    <input type="hidden" id="h" name="h" />
                  </div>
                  <script type="text/javascript">
                    $(function () {
                      $("#modal-upload-picture").modal();
                      window.history.pushState("", "", "/settings/picture/");
                    });
                  </script>
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-default" data-dismiss="modal">{% trans 'Close' %}</button>
                  <button type="submit" class="btn btn-primary">{% trans 'Save changes' %}</button>
                </div>
              </div>
            </div>
          </div>
        </form>
      {% endif %}
    </div>
  </div>
{% endblock main %}

templates/myuserprofile/profile.html
{% extends "user_home.html" %}
{% load imagekit %}
{% load staticfiles %}

{% block css_2 %}
	<link rel="stylesheet" type="text/css" href={% static 'css/profile_styler.css' %}>
	<link rel="stylesheet" type="text/css" href={% static 'css/form_styler.css' %}>
	{% block css_3 %}
	{% endblock %}
{% endblock %}

{% block menu_content_links %}
	<h3 class="ent_title"><a href="{% url 'myuserprofile:profile' page_user.slug %}">{{ page_user }}</a></h3>
	<a href="{% url 'myuserprofile:profile' page_user.slug %}"><li class="link_content">About</li></a>
	<!--
	<li class="link_content aj" class="a_menu" data-link="{% url 'myuserprofile:profile' page_user.slug %}">About</li>-->
{% endblock %}

{% block left_menu %}
	<div id="left_ent">
		<img id="ent_img" src="/images/{{ page_user_profile.get_image }}" alt="{{ page_user }}">
		{% ifnotequal page_user user %}
		<form action="{% if relationship_status == 'F' %}{% url 'myuserprofile:relationships:unfollow' %}{% else %}{% url 'myuserprofile:relationships:follow'  %}{% endif %}" method="POST">
			{% csrf_token %}
		<input type="hidden" value="{{ page_user.id }}" name="to_user">
		<input type="submit" class="follow" value="{% if relationship_status == 'F' %}Unfollow{% else %}Follow{% endif %}">	
		</form>
		{% endifnotequal %}
	</div>
{% endblock %}



{% block mid_content %}
<section id="mid_content_box">
	{% ifequal page_user user %}
		<iframe id="edit_frame" class="inner_frame" name="edit_frame" src=""></iframe>
	{% endifequal %}
	<dl class="profile_box">
	{% ifequal page_user user %}
	<a class="pop_link_left framer" href="{% url 'myuserprofile:profile_edit' %}" target="edit_frame">edit</a>
	{% endifequal %}
		<div class="info_box half">
			<dt class="info_name">Full Name :</dt>
			<dd class="info_data">{{ page_user_profile.get_screen_name }}</dd>
		</div>
		<div class="info_box half">
			<dt class="info_name">Works At :</dt>
			<dd class="info_data ilog">{{ page_user.enterprise }}</dd>
		</div>
		<div class="info_box half">
			<dt class="info_name">Position :</dt>
			<dd class="info_data">{{ page_user_profile.job_position }}</dd>
		</div>
		<div class="info_box">
			<dt class="info_name">Experienced in :</dt>
			<dd class="info_data wide">{{ page_user_profile.experience }}</dd>
		</div>
		<div class="info_box half">
			<dt class="info_name">Skillset :</dt>
			<dd class="info_data">
			{% for skills in skillset %}
				<ul>
					<li>{{skills}}</li>
				</ul>
			{% endfor %}
			</dd>
		</div>
	</dl>
</section>
{% endblock %}

{% block scripts %}
	<script type="text/javascript">
		$('.aj').click(function(){
			var $this = $(this);
			var url = $(this).data('link');
			$('#mid_content_box').load(url);
			
			function hido(){
				var hide = $('.profile').find('.hidden');
				var hide_this = hide.data('hide');
				$('.'+hide_this).text('');
			}
		});
		$('.aj_f').click(function(){
			var $this = $(this);
			var url = $(this).data('link');
			var form = $('#form_edit').serialize();
			console.log(form,url);
			//$('#mid_content_box').load(url);
			
			function hido(){
				var hide = $('.profile').find('.hidden');
				var hide_this = hide.data('hide');
				$('.'+hide_this).text('');
			}
		});
	</script>
{% endblock %}

templates/myuserprofile/profile_edit.html
{% extends 'frame.html' %}
{% load staticfiles %}

{% block css %}
	<link href={% static 'css/form_styler.css' %} media="all" rel="stylesheet" type="text/css" />
{% endblock %}

{% block content %}
<section id="content_profile_edit">
	<header class="header_form">
		<h2>Update yours Profile</h2>
	</header>
	<form class="" enctype="multipart/form-data" action="{% url 'myuserprofile:profile_edit' %}" target="_parent" method="POST" role="form" >
		<input class="pop_link_left" type="submit" value="Save">
		<ul class="form_edit">
			{{ form.as_ul }}
			{% csrf_token %}
		</ul>
	</form>
</section>
{% endblock %}

templates/myuserprofile/skillset.html
<div class="edit">edit</div>
<dl class="profile_box">
	<dt class="info_name">Full Name :</dt>
	<dd class="info_data">{{ page_user_profile.get_screen_name }}</dd>
	<dt class="info_name">Works as :</dt>
	<dd class="info_data">{{ page_user_profile.job_position }}</dd>
	<dt class="info_name">At :</dt>
	<dd class="info_data ilog">{{ page_user.enterprise }}</dd>
	<dt class="info_name">Experienced in :</dt>
	<dd class="info_data wide">{{ page_user_profile.experience }}</dd>
</dl>